

// This file was AUTO GENERATED by '/wrapper/gen.js'.
// The configs was under 'dev/wrapper_configs', and the scheme is 'src/buffer.json'.

#include "buffer.h"
#include "buffer.inc"

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "types.h"
#include <errno.h>
#include <stdbool.h>

static void napi_cyrntest_throw_error(napi_env env, int errnum){
    napi_value error;
    napi_create_string_utf8(env, "Internal Error.", NAPI_AUTO_LENGTH, &error);
    napi_throw(env, error);
}

#define napi_cyrntest_max(a, b) ((a) > (b) ? (a) : (b))


napi_value wrapper_buffer_isBase64String(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    string var0;
napi_get_value_string_utf8(env, args[0], NULL, 0, &var0.length);
var0.data = (char*)malloc(var0.length + 1);
size_t napi_new_str_copied_0;
napi_get_value_string_utf8(env, args[0], var0.data, var0.length + 1, &napi_new_str_copied_0);


    errno = 0;
    int retval = buffer_isBase64String(var0);

    if(var0.data != NULL){
    free(var0.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_boolean(env, retval, &result);
return result;
}

napi_value wrapper_buffer_isLatin1String(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    wstring var0;
napi_get_value_string_utf16(env, args[0], NULL, 0, &var0.length);
var0.data = (uint16_t*)malloc((var0.length + 1) * sizeof(uint16_t));
size_t napi_new_str_copied_0;
napi_get_value_string_utf16(env, args[0], var0.data, var0.length + 1, &napi_new_str_copied_0);


    errno = 0;
    int retval = buffer_isLatin1String(var0);

    if(var0.data != NULL){
    free(var0.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_boolean(env, retval, &result);
return result;
}

napi_value wrapper_buffer_byteLengthUtf8(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    string var0;
napi_get_value_string_utf8(env, args[0], NULL, 0, &var0.length);
var0.data = (char*)malloc(var0.length + 1);
size_t napi_new_str_copied_0;
napi_get_value_string_utf8(env, args[0], var0.data, var0.length + 1, &napi_new_str_copied_0);


    errno = 0;
    int64_t retval = buffer_byteLengthUtf8(var0);

    if(var0.data != NULL){
    free(var0.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_memcmp(napi_env env, napi_callback_info info) {
    size_t argc = 5;
    napi_value args[napi_cyrntest_max(5, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
array_buffer var1;
// napi_create_reference(env, args[1], 1, var1.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[1], &var1.data, &var1.size);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
int64_t var3;
napi_get_value_int64(env, args[3], &var3);
int64_t var4;
napi_get_value_int64(env, args[4], &var4);


    errno = 0;
    int32_t retval = buffer_memcmp(var0, var1, var2, var3, var4);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
// napi_delete_reference(env, var1.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int32(env, retval, &result);
return result;
}

napi_value wrapper_buffer_memmem(napi_env env, napi_callback_info info) {
    size_t argc = 4;
    napi_value args[napi_cyrntest_max(4, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
array_buffer var1;
// napi_create_reference(env, args[1], 1, var1.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[1], &var1.data, &var1.size);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
bool var3;
napi_get_value_bool(env, args[3], &var3);


    errno = 0;
    int64_t retval = buffer_memmem(var0, var1, var2, var3);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
// napi_delete_reference(env, var1.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_swap16(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);


    errno = 0;
    buffer_swap16(var0);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_undefined(env, &result);
return result;
}

napi_value wrapper_buffer_swap32(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);


    errno = 0;
    buffer_swap32(var0);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_undefined(env, &result);
return result;
}

napi_value wrapper_buffer_swap64(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);


    errno = 0;
    buffer_swap64(var0);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_undefined(env, &result);
return result;
}

napi_value wrapper_buffer_isUtf8(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);


    errno = 0;
    int retval = buffer_isUtf8(var0);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_boolean(env, retval, &result);
return result;
}

napi_value wrapper_buffer_isAscii(napi_env env, napi_callback_info info) {
    size_t argc = 1;
    napi_value args[napi_cyrntest_max(1, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);


    errno = 0;
    int retval = buffer_isAscii(var0);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_get_boolean(env, retval, &result);
return result;
}

napi_value wrapper_buffer_kMaxLength(napi_env env, napi_callback_info info) {
    size_t argc = 0;
    napi_value args[napi_cyrntest_max(0, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    

    errno = 0;
    int64_t retval = buffer_kMaxLength();

    

    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_base64Slice(napi_env env, napi_callback_info info) {
    size_t argc = 4;
    napi_value args[napi_cyrntest_max(4, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
int64_t var1;
napi_get_value_int64(env, args[1], &var1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
bool var3;
napi_get_value_bool(env, args[3], &var3);


    errno = 0;
    string retval = buffer_base64Slice(var0, var1, var2, var3);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        if(retval.data != NULL){
    free(retval.data);
}
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    napi_value result;
napi_create_string_utf8(env, retval.data, retval.length, &result);
    if(retval.data != NULL){
    free(retval.data);
}
    return result;
}

napi_value wrapper_buffer_latin1Slice(napi_env env, napi_callback_info info) {
    size_t argc = 4;
    napi_value args[napi_cyrntest_max(4, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
int64_t var1;
napi_get_value_int64(env, args[1], &var1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
bool var3;
napi_get_value_bool(env, args[3], &var3);


    errno = 0;
    wstring retval = buffer_latin1Slice(var0, var1, var2, var3);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        if(retval.data != NULL){
    free(retval.data);
}
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    napi_value result;
napi_create_string_utf16(env, retval.data, retval.length, &result);
    if(retval.data != NULL){
    free(retval.data);
}
    return result;
}

napi_value wrapper_buffer_hexSlice(napi_env env, napi_callback_info info) {
    size_t argc = 3;
    napi_value args[napi_cyrntest_max(3, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
int64_t var1;
napi_get_value_int64(env, args[1], &var1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);


    errno = 0;
    string retval = buffer_hexSlice(var0, var1, var2);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        if(retval.data != NULL){
    free(retval.data);
}
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    napi_value result;
napi_create_string_utf8(env, retval.data, retval.length, &result);
    if(retval.data != NULL){
    free(retval.data);
}
    return result;
}

napi_value wrapper_buffer_ucs2Slice(napi_env env, napi_callback_info info) {
    size_t argc = 3;
    napi_value args[napi_cyrntest_max(3, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
int64_t var1;
napi_get_value_int64(env, args[1], &var1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);


    errno = 0;
    wstring retval = buffer_ucs2Slice(var0, var1, var2);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        if(retval.data != NULL){
    free(retval.data);
}
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    napi_value result;
napi_create_string_utf16(env, retval.data, retval.length, &result);
    if(retval.data != NULL){
    free(retval.data);
}
    return result;
}

napi_value wrapper_buffer_utf8Slice(napi_env env, napi_callback_info info) {
    size_t argc = 3;
    napi_value args[napi_cyrntest_max(3, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
int64_t var1;
napi_get_value_int64(env, args[1], &var1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);


    errno = 0;
    string retval = buffer_utf8Slice(var0, var1, var2);

    // napi_delete_reference(env, var0.ref); // TODO: fix this


    if(errno != 0) {
        if(retval.data != NULL){
    free(retval.data);
}
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    napi_value result;
napi_create_string_utf8(env, retval.data, retval.length, &result);
    if(retval.data != NULL){
    free(retval.data);
}
    return result;
}

napi_value wrapper_buffer_base64Write(napi_env env, napi_callback_info info) {
    size_t argc = 5;
    napi_value args[napi_cyrntest_max(5, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
string var1;
napi_get_value_string_utf8(env, args[1], NULL, 0, &var1.length);
var1.data = (char*)malloc(var1.length + 1);
size_t napi_new_str_copied_1;
napi_get_value_string_utf8(env, args[1], var1.data, var1.length + 1, &napi_new_str_copied_1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
int64_t var3;
napi_get_value_int64(env, args[3], &var3);
bool var4;
napi_get_value_bool(env, args[4], &var4);


    errno = 0;
    int64_t retval = buffer_base64Write(var0, var1, var2, var3, var4);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
if(var1.data != NULL){
    free(var1.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_hexWrite(napi_env env, napi_callback_info info) {
    size_t argc = 4;
    napi_value args[napi_cyrntest_max(4, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
string var1;
napi_get_value_string_utf8(env, args[1], NULL, 0, &var1.length);
var1.data = (char*)malloc(var1.length + 1);
size_t napi_new_str_copied_1;
napi_get_value_string_utf8(env, args[1], var1.data, var1.length + 1, &napi_new_str_copied_1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
int64_t var3;
napi_get_value_int64(env, args[3], &var3);


    errno = 0;
    int64_t retval = buffer_hexWrite(var0, var1, var2, var3);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
if(var1.data != NULL){
    free(var1.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_ucs2Write(napi_env env, napi_callback_info info) {
    size_t argc = 4;
    napi_value args[napi_cyrntest_max(4, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
wstring var1;
napi_get_value_string_utf16(env, args[1], NULL, 0, &var1.length);
var1.data = (uint16_t*)malloc((var1.length + 1) * sizeof(uint16_t));
size_t napi_new_str_copied_1;
napi_get_value_string_utf16(env, args[1], var1.data, var1.length + 1, &napi_new_str_copied_1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
int64_t var3;
napi_get_value_int64(env, args[3], &var3);


    errno = 0;
    int64_t retval = buffer_ucs2Write(var0, var1, var2, var3);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
if(var1.data != NULL){
    free(var1.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_latin1Write(napi_env env, napi_callback_info info) {
    size_t argc = 5;
    napi_value args[napi_cyrntest_max(5, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
wstring var1;
napi_get_value_string_utf16(env, args[1], NULL, 0, &var1.length);
var1.data = (uint16_t*)malloc((var1.length + 1) * sizeof(uint16_t));
size_t napi_new_str_copied_1;
napi_get_value_string_utf16(env, args[1], var1.data, var1.length + 1, &napi_new_str_copied_1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
int64_t var3;
napi_get_value_int64(env, args[3], &var3);
bool var4;
napi_get_value_bool(env, args[4], &var4);


    errno = 0;
    int64_t retval = buffer_latin1Write(var0, var1, var2, var3, var4);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
if(var1.data != NULL){
    free(var1.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}

napi_value wrapper_buffer_utf8Write(napi_env env, napi_callback_info info) {
    size_t argc = 4;
    napi_value args[napi_cyrntest_max(4, 1)];
    napi_get_cb_info(env, info, &argc, args, NULL, NULL);

    array_buffer var0;
// napi_create_reference(env, args[0], 1, var0.ref);  // TODO: fix this
napi_get_arraybuffer_info(env, args[0], &var0.data, &var0.size);
string var1;
napi_get_value_string_utf8(env, args[1], NULL, 0, &var1.length);
var1.data = (char*)malloc(var1.length + 1);
size_t napi_new_str_copied_1;
napi_get_value_string_utf8(env, args[1], var1.data, var1.length + 1, &napi_new_str_copied_1);
int64_t var2;
napi_get_value_int64(env, args[2], &var2);
int64_t var3;
napi_get_value_int64(env, args[3], &var3);


    errno = 0;
    int64_t retval = buffer_utf8Write(var0, var1, var2, var3);

    // napi_delete_reference(env, var0.ref); // TODO: fix this
if(var1.data != NULL){
    free(var1.data);
}


    if(errno != 0) {
        
        napi_cyrntest_throw_error(env, errno);
        return NULL; 
    }

    
    
    napi_value result;
napi_create_int64(env, retval, &result);
return result;
}




void* wrapperFunctions[] = {
    (void*)wrapper_buffer_isBase64String,
    (void*)wrapper_buffer_isLatin1String,
    (void*)wrapper_buffer_byteLengthUtf8,
    (void*)wrapper_buffer_memcmp,
    (void*)wrapper_buffer_memmem,
    (void*)wrapper_buffer_swap16,
    (void*)wrapper_buffer_swap32,
    (void*)wrapper_buffer_swap64,
    (void*)wrapper_buffer_isUtf8,
    (void*)wrapper_buffer_isAscii,
    (void*)wrapper_buffer_kMaxLength,
    (void*)wrapper_buffer_base64Slice,
    (void*)wrapper_buffer_latin1Slice,
    (void*)wrapper_buffer_hexSlice,
    (void*)wrapper_buffer_ucs2Slice,
    (void*)wrapper_buffer_utf8Slice,
    (void*)wrapper_buffer_base64Write,
    (void*)wrapper_buffer_hexWrite,
    (void*)wrapper_buffer_ucs2Write,
    (void*)wrapper_buffer_latin1Write,
    (void*)wrapper_buffer_utf8Write,
};
   // function array of wrappers

const char* wrapperNames[] = {
    "isBase64String",
    "isLatin1String",
    "byteLengthUtf8",
    "memcmp",
    "memmem",
    "swap16",
    "swap32",
    "swap64",
    "isUtf8",
    "isAscii",
    "kMaxLength",
    "base64Slice",
    "latin1Slice",
    "hexSlice",
    "ucs2Slice",
    "utf8Slice",
    "base64Write",
    "hexWrite",
    "ucs2Write",
    "latin1Write",
    "utf8Write",
};
   // array of wrapper names

/* int wrapperParamCounts[] = {
    1,
    1,
    1,
    5,
    4,
    1,
    1,
    1,
    1,
    1,
    0,
    4,
    4,
    3,
    3,
    3,
    5,
    4,
    4,
    5,
    4,
};
 */   // array of wrapper parameter counts

napi_value Initbuffer(napi_env env, napi_value exports) {
    for (int i = 0; i < 21; i++) {
        napi_value fn;
        napi_create_function(env, wrapperNames[i], NAPI_AUTO_LENGTH, wrapperFunctions[i], NULL, &fn);
        napi_set_named_property(env, exports, wrapperNames[i], fn);
    }

    return exports;
}

NAPI_MODULE(NAPI_MODULE_buffer, Initbuffer)