

// This file was AUTO GENERATED by '/wrapper/gen.js'.
// The configs was under 'dev/wrapper_configs', and the scheme is 'src/buffer.json'.

#ifndef BINDINGS_buffer_H
#define BINDINGS_buffer_H

#include <node_api.h>

napi_value Initbuffer(napi_env env, napi_value exports);

#endif   // BINDINGS_buffer_H