
const path = require('path')
const fs = require('fs')

const {generateWrapperC, generateWrapperH} = require('./generateWrapperCH.js')

function gen(configPath, schemePath, outputPath) {

    let header = `

// This file was AUTO GENERATED by '/wrapper/gen.js'.
// The configs was under '${configPath}', and the scheme is '${schemePath}'.

`

    const scheme = JSON.parse(fs.readFileSync(schemePath, 'utf-8'));

    fs.writeFileSync(
        path.join(outputPath, scheme.name+'.c'),
        header+generateWrapperC(scheme, configPath),
        'utf-8'
    )

    fs.writeFileSync(
        path.join(outputPath, scheme.name+'.h'),
        header+generateWrapperH(scheme, configPath),
        'utf-8'
    )
}

gen('dev/wrapper_configs', 'src/buffer.json', 'dev/src')